[package]
name = "test_project"
version = "0.1.0"
edition = "2021"

[dependencies]
acton-reactive = { version = "1.1.0-beta.1" }
tokio = { version = "1.40.0", features = ["macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
