[package]
name = "acton_test_macro"
version = "1.0.0-alpha.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
tracing = "0.1.40"
parking_lot = "0.12.3"
